INSERT OR IGNORE INTO "Skill" ("id", "name") VALUES
('skill_accessibility', 'Accessibility'),
('skill_css', 'CSS'),
('skill_design_system', 'Design system'),
('skill_documentation', 'Documentation'),
('skill_erc_4337', 'ERC-4337'),
('skill_figma', 'Figma'),
('skill_foundry', 'Foundry'),
('skill_graphql', 'GraphQL'),
('skill_hardhat', 'Hardhat'),
('skill_javascript', 'JavaScript'),
('skill_mobile', 'Mobile'),
('skill_next_js', 'Next.js'),
('skill_node_js', 'Node.js'),
('skill_postgresql', 'PostgreSQL'),
('skill_product', 'Product'),
('skill_react', 'React'),
('skill_research', 'Research'),
('skill_rust', 'Rust'),
('skill_security', 'Security'),
('skill_solidity', 'Solidity'),
('skill_technical_writing', 'Technical writing'),
('skill_testing', 'Testing'),
('skill_typescript', 'TypeScript'),
('skill_ui_ux', 'UI / UX'),
('skill_walletconnect', 'WalletConnect'),
('skill_viem', 'viem'),
('skill_wagmi', 'wagmi');
